-- MySQL Script generated by MySQL Workbench
-- 08/04/17 22:20:30
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_name` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `address` VARCHAR(255) NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_name`),
  UNIQUE INDEX `user_name_UNIQUE` (`user_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplier` (
  `s_id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NULL,
  `user_user_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`s_id`, `user_user_name`),
  INDEX `fk_supplier_user_idx` (`user_user_name` ASC),
  CONSTRAINT `fk_supplier_user`
    FOREIGN KEY (`user_user_name`)
    REFERENCES `mydb`.`user` (`user_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `e_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `tel` INT NULL,
  `type` VARCHAR(45) NOT NULL,
  `user_user_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`e_id`, `user_user_name`),
  INDEX `fk_employee_user1_idx` (`user_user_name` ASC),
  CONSTRAINT `fk_employee_user1`
    FOREIGN KEY (`user_user_name`)
    REFERENCES `mydb`.`user` (`user_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dealer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dealer` (
  `d_id` INT NOT NULL AUTO_INCREMENT,
  `shop_name` VARCHAR(255) NULL,
  `tel` INT NULL,
  `user_user_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`d_id`, `user_user_name`),
  INDEX `fk_dealer_user1_idx` (`user_user_name` ASC),
  CONSTRAINT `fk_dealer_user1`
    FOREIGN KEY (`user_user_name`)
    REFERENCES `mydb`.`user` (`user_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`regular_customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`regular_customer` (
  `r_id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(255) NULL,
  `tel` INT NULL,
  `user_user_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`r_id`, `user_user_name`),
  INDEX `fk_regular_customer_user1_idx` (`user_user_name` ASC),
  CONSTRAINT `fk_regular_customer_user1`
    FOREIGN KEY (`user_user_name`)
    REFERENCES `mydb`.`user` (`user_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`import_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`import_manager` (
  `employee_e_id` INT NOT NULL,
  PRIMARY KEY (`employee_e_id`),
  CONSTRAINT `fk_import_manager_employee1`
    FOREIGN KEY (`employee_e_id`)
    REFERENCES `mydb`.`employee` (`e_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`system_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`system_admin` (
  `employee_e_id` INT NOT NULL,
  PRIMARY KEY (`employee_e_id`),
  CONSTRAINT `fk_system_admin_employee1`
    FOREIGN KEY (`employee_e_id`)
    REFERENCES `mydb`.`employee` (`e_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sales_executive`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sales_executive` (
  `employee_e_id` INT NOT NULL,
  PRIMARY KEY (`employee_e_id`),
  CONSTRAINT `fk_sales_executive_employee1`
    FOREIGN KEY (`employee_e_id`)
    REFERENCES `mydb`.`employee` (`e_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stock_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stock_manager` (
  `employee_e_id` INT NOT NULL,
  PRIMARY KEY (`employee_e_id`),
  CONSTRAINT `fk_stock_manager_employee1`
    FOREIGN KEY (`employee_e_id`)
    REFERENCES `mydb`.`employee` (`e_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chief_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chief_manager` (
  `employee_e_id` INT NOT NULL,
  PRIMARY KEY (`employee_e_id`),
  CONSTRAINT `fk_chief_manager_employee1`
    FOREIGN KEY (`employee_e_id`)
    REFERENCES `mydb`.`employee` (`e_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purchase_requisition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase_requisition` (
  `pr_no` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `status` VARCHAR(45) NULL,
  `supplier_s_id` INT NOT NULL,
  `import_manager_employee_e_id` INT NOT NULL,
  PRIMARY KEY (`pr_no`, `supplier_s_id`, `import_manager_employee_e_id`),
  INDEX `fk_purchase_requisition_supplier1_idx` (`supplier_s_id` ASC),
  INDEX `fk_purchase_requisition_import_manager1_idx` (`import_manager_employee_e_id` ASC),
  CONSTRAINT `fk_purchase_requisition_supplier1`
    FOREIGN KEY (`supplier_s_id`)
    REFERENCES `mydb`.`supplier` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_purchase_requisition_import_manager1`
    FOREIGN KEY (`import_manager_employee_e_id`)
    REFERENCES `mydb`.`import_manager` (`employee_e_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sales_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sales_order` (
  `sord_no` INT NOT NULL AUTO_INCREMENT,
  `total_amount` INT NULL,
  `date` DATE NOT NULL,
  `status` VARCHAR(45) NULL,
  `dealer_d_id` INT NOT NULL,
  `regular_customer_r_id` INT NOT NULL,
  PRIMARY KEY (`sord_no`, `dealer_d_id`, `regular_customer_r_id`),
  INDEX `fk_sales_order_dealer1_idx` (`dealer_d_id` ASC),
  INDEX `fk_sales_order_regular_customer1_idx` (`regular_customer_r_id` ASC),
  CONSTRAINT `fk_sales_order_dealer1`
    FOREIGN KEY (`dealer_d_id`)
    REFERENCES `mydb`.`dealer` (`d_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_order_regular_customer1`
    FOREIGN KEY (`regular_customer_r_id`)
    REFERENCES `mydb`.`regular_customer` (`r_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoice` (
  `invoice_no` INT NOT NULL AUTO_INCREMENT,
  `net_amount` INT NULL,
  `discount` INT NULL,
  `invoice_notice` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `sub_total` INT NULL,
  `date` DATE NOT NULL,
  `sales_executive_employee_e_id` INT NOT NULL,
  `sales_order_sord_no` INT NOT NULL,
  PRIMARY KEY (`invoice_no`, `sales_executive_employee_e_id`, `sales_order_sord_no`),
  INDEX `fk_invoice_sales_executive1_idx` (`sales_executive_employee_e_id` ASC),
  INDEX `fk_invoice_sales_order1_idx` (`sales_order_sord_no` ASC),
  CONSTRAINT `fk_invoice_sales_executive1`
    FOREIGN KEY (`sales_executive_employee_e_id`)
    REFERENCES `mydb`.`sales_executive` (`employee_e_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_sales_order1`
    FOREIGN KEY (`sales_order_sord_no`)
    REFERENCES `mydb`.`sales_order` (`sord_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`purchase_confirmation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`purchase_confirmation` (
  `pc_no` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  `purchase_requisition_pr_no` INT NOT NULL,
  PRIMARY KEY (`pc_no`, `purchase_requisition_pr_no`),
  INDEX `fk_purchase_confirmation_purchase_requisition1_idx` (`purchase_requisition_pr_no` ASC),
  CONSTRAINT `fk_purchase_confirmation_purchase_requisition1`
    FOREIGN KEY (`purchase_requisition_pr_no`)
    REFERENCES `mydb`.`purchase_requisition` (`pr_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`quatation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`quatation` (
  `q_no` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `qty` INT NULL,
  `regular_customer_r_id` INT NOT NULL,
  PRIMARY KEY (`q_no`, `regular_customer_r_id`),
  INDEX `fk_quatation_regular_customer1_idx` (`regular_customer_r_id` ASC),
  CONSTRAINT `fk_quatation_regular_customer1`
    FOREIGN KEY (`regular_customer_r_id`)
    REFERENCES `mydb`.`regular_customer` (`r_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tire` (
  `t_id` INT NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(45) NULL,
  `tire_size` VARCHAR(45) NULL,
  `brand_name` VARCHAR(45) NULL,
  `quantity` INT NULL,
  `unit_price` INT NULL,
  `status` VARCHAR(45) NULL,
  `supplier_s_id` INT NOT NULL,
  PRIMARY KEY (`t_id`, `supplier_s_id`),
  INDEX `fk_tire_supplier1_idx` (`supplier_s_id` ASC),
  CONSTRAINT `fk_tire_supplier1`
    FOREIGN KEY (`supplier_s_id`)
    REFERENCES `mydb`.`supplier` (`s_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '					';


-- -----------------------------------------------------
-- Table `mydb`.`pr_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pr_item` (
  `tire_t_id` INT NOT NULL,
  `purchase_requisition_pr_no` INT NOT NULL,
  `qty` INT NULL,
  PRIMARY KEY (`tire_t_id`, `purchase_requisition_pr_no`),
  INDEX `fk_tire_has_purchase_requisition_purchase_requisition1_idx` (`purchase_requisition_pr_no` ASC),
  INDEX `fk_tire_has_purchase_requisition_tire1_idx` (`tire_t_id` ASC),
  CONSTRAINT `fk_tire_has_purchase_requisition_tire1`
    FOREIGN KEY (`tire_t_id`)
    REFERENCES `mydb`.`tire` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tire_has_purchase_requisition_purchase_requisition1`
    FOREIGN KEY (`purchase_requisition_pr_no`)
    REFERENCES `mydb`.`purchase_requisition` (`pr_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pc_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pc_item` (
  `tire_t_id` INT NOT NULL,
  `purchase_confirmation_pc_no` INT NOT NULL,
  `unit_price` INT NULL,
  `qty` INT NULL,
  PRIMARY KEY (`tire_t_id`, `purchase_confirmation_pc_no`),
  INDEX `fk_tire_has_purchase_confirmation_purchase_confirmation1_idx` (`purchase_confirmation_pc_no` ASC),
  INDEX `fk_tire_has_purchase_confirmation_tire1_idx` (`tire_t_id` ASC),
  CONSTRAINT `fk_tire_has_purchase_confirmation_tire1`
    FOREIGN KEY (`tire_t_id`)
    REFERENCES `mydb`.`tire` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tire_has_purchase_confirmation_purchase_confirmation1`
    FOREIGN KEY (`purchase_confirmation_pc_no`)
    REFERENCES `mydb`.`purchase_confirmation` (`pc_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`invoice_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`invoice_item` (
  `tire_t_id` INT NOT NULL,
  `invoice_idinvoice_no` INT NOT NULL,
  PRIMARY KEY (`tire_t_id`, `invoice_idinvoice_no`),
  INDEX `fk_tire_has_invoice_invoice1_idx` (`invoice_idinvoice_no` ASC),
  INDEX `fk_tire_has_invoice_tire1_idx` (`tire_t_id` ASC),
  CONSTRAINT `fk_tire_has_invoice_tire1`
    FOREIGN KEY (`tire_t_id`)
    REFERENCES `mydb`.`tire` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tire_has_invoice_invoice1`
    FOREIGN KEY (`invoice_idinvoice_no`)
    REFERENCES `mydb`.`invoice` (`invoice_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order_item` (
  `tire_t_id` INT NOT NULL,
  `sales_order_sord_no` INT NOT NULL,
  `qty` INT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`tire_t_id`, `sales_order_sord_no`),
  INDEX `fk_tire_has_sales_order_sales_order1_idx` (`sales_order_sord_no` ASC),
  INDEX `fk_tire_has_sales_order_tire1_idx` (`tire_t_id` ASC),
  CONSTRAINT `fk_tire_has_sales_order_tire1`
    FOREIGN KEY (`tire_t_id`)
    REFERENCES `mydb`.`tire` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tire_has_sales_order_sales_order1`
    FOREIGN KEY (`sales_order_sord_no`)
    REFERENCES `mydb`.`sales_order` (`sord_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`quatation_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`quatation_item` (
  `tire_t_id` INT NOT NULL,
  `quatation_q_no` INT NOT NULL,
  PRIMARY KEY (`tire_t_id`, `quatation_q_no`),
  INDEX `fk_tire_has_quatation_quatation1_idx` (`quatation_q_no` ASC),
  INDEX `fk_tire_has_quatation_tire1_idx` (`tire_t_id` ASC),
  CONSTRAINT `fk_tire_has_quatation_tire1`
    FOREIGN KEY (`tire_t_id`)
    REFERENCES `mydb`.`tire` (`t_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tire_has_quatation_quatation1`
    FOREIGN KEY (`quatation_q_no`)
    REFERENCES `mydb`.`quatation` (`q_no`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
